// Code generated by runnerq-spec tools/gen from protocol/conductor/conductor.schema.json. DO NOT EDIT.

/** The agent's SDK. */
export interface SDKInfo {
  name: string;
  version: string;
  /** go, typescript, ... */
  language: string;
}

/** The worker process behind a session. */
export interface ExecutorInfo {
  /**
   * Stable for the process; a newer session with the same id supersedes an
   * older one.
   */
  id: string;
  hostname?: string;
  queues?: string[];
  activity_types?: string[];
  max_concurrency?: number;
  started_at?: string;
  labels?: Record<string, string>;
}

/** An activity in flight on an executor. */
export interface RunningActivity {
  activity_id: string;
  type: string;
  attempt: number;
  started_at: string;
}

/** The counts of an executor's activity outcomes since it started. */
export interface ExecutorCounters {
  claimed: number;
  succeeded: number;
  retried: number;
  failed: number;
  timed_out: number;
  dead_lettered: number;
  claims_lost: number;
}

/**
 * An executor's live, in-memory state: executor.describe's answer, and
 * (without running) executor.report's data.
 */
export interface ExecutorState {
  id: string;
  uptime_ms: number;
  max_concurrency: number;
  in_flight: number;
  /**
   * On executor.describe and hosted reports, [] when nothing runs; omitted
   * from executor.report.
   */
  running?: RunningActivity[];
  /** How long the latest activity waited to start after it was due. */
  claim_lag_ms: number;
  heartbeat_failures: number;
  draining: boolean;
  counters: ExecutorCounters;
}

/**
 * A hosted worker's heartbeat to the data plane (PUT /v1/executors/{id}, with
 * the store key; see the storage protocol): its hello's sdk and executor, and
 * its state with running.
 */
export interface ExecutorReport {
  sdk: SDKInfo;
  executor: ExecutorInfo;
  state: ExecutorState;
}