// Code generated by runnerq-spec tools/gen from protocol/storage/executor_report.schema.json. DO NOT EDIT.

/**
 * A worker's heartbeat (PUT /v1/executors/{id}, with the store key) for
 * RunnerQ Cloud's Fleet, in a conductor agent's shapes: its hello's sdk and
 * executor, and its executor.report state.
 */
export interface ExecutorReport {
  sdk: SDKInfo;
  executor: ExecutorInfo;
  state: ExecutorState;
}

export interface SDKInfo {
  name: string;
  version: string;
  language: string;
}

/** Who the executor is. */
export interface ExecutorInfo {
  /** Stable for the process. */
  id: string;
  hostname?: string;
  /** Exactly one, on the data plane. */
  queues?: string[];
  activity_types?: string[];
  max_concurrency?: number;
  started_at?: string;
  labels?: Record<string, string>;
}

export interface ExecutorState {
  /** Empty or the executor's id. */
  id: string;
  uptime_ms: number;
  max_concurrency: number;
  in_flight: number;
  running?: RunningActivity[];
  claim_lag_ms: number;
  heartbeat_failures: number;
  draining: boolean;
  counters?: Counters;
}

export interface RunningActivity {
  activity_id: string;
  type: string;
  attempt: number;
  started_at: string;
}

/** Activity outcomes since the executor started. */
export interface Counters {
  claimed: number;
  succeeded: number;
  retried: number;
  failed: number;
  timed_out: number;
  dead_lettered: number;
  claims_lost: number;
}