// Code generated by runnerq-spec tools/gen from protocol/storage/storage.schema.json. DO NOT EDIT.

/** The RunnerQ-Storage-Version header's value. */
export const storageVersion = "1";

/** The wire codes of the storage error kinds, indexed by kind number. */
export const errorCodes = [
  "unavailable",
  "conflict",
  "not_found",
  "internal",
  "serialization",
  "configuration",
  "timeout",
  "duplicate_activity",
  "idempotency_conflict",
  "claim_lost",
  "checkpoint_conflict",
  "invalid_argument",
  "unsupported",
] as const;

/**
 * A UUID, lowercase in the 8-4-4-4-12 form. Absent or null decodes as the nil
 * UUID.
 */
export type UUID = string;

/**
 * RFC 3339 with up to nanosecond precision (Go's time.RFC3339Nano). The zero
 * time is 0001-01-01T00:00:00Z.
 */
export type Timestamp = string;

/** A duration in integer nanoseconds. */
export type Duration = number;

/**
 * Any JSON value, carried as is: a payload, result or detail. Absent and null
 * are the same.
 */
export type RawJSON = unknown;

/** 1 low, 2 normal, 3 high, 4 critical. */
export type Priority = 1 | 2 | 3 | 4;

/**
 * 0 allow reuse, 1 return existing, 2 allow reuse on failure, 3 no reuse.
 */
export type IdempotencyBehavior = 0 | 1 | 2 | 3;

/** 0 ok, 1 error. */
export type ResultState = 0 | 1;

/**
 * A storage error kind's name (constants.json storage_error_kind). Clients
 * decode the code, not the HTTP status; an unknown code is a configuration
 * error.
 */
export type ErrorCode = "unavailable" | "conflict" | "not_found" | "internal" | "serialization" | "configuration" | "timeout" | "duplicate_activity" | "idempotency_conflict" | "claim_lost" | "checkpoint_conflict" | "invalid_argument" | "unsupported";

/** Every ErrorCode. */
export const errorCodeValues = ["unavailable", "conflict", "not_found", "internal", "serialization", "configuration", "timeout", "duplicate_activity", "idempotency_conflict", "claim_lost", "checkpoint_conflict", "invalid_argument", "unsupported"] as const;

export interface ErrorBody {
  code: ErrorCode;
  message: string;
  /** The input an invalid_argument or unsupported error is about. */
  field?: string;
}

/**
 * Every response body: result on success (HTTP 200), error otherwise.
 * Operations without a result return null.
 */
export interface ResponseBody {
  result?: RawJSON;
  error?: ErrorBody;
}

export interface ActivityResult {
  Data?: RawJSON;
  State: ResultState;
  /** Data's encoding; empty means json-v1. */
  Serialization?: string;
}

export interface QueuedActivity {
  ID: UUID;
  ActivityType: string;
  Payload?: RawJSON;
  Priority: Priority;
  MaxRetries: number;
  RetryCount: number;
  TimeoutSeconds: number;
  RetryDelaySeconds: number;
  MaxRetryDelaySeconds: number;
  ScheduledAt?: Timestamp | null;
  Metadata?: Record<string, string> | null;
  IdempotencyKey?: IdempotencyKeyConfig | null;
  CreatedAt: Timestamp;
  ParentActivityID?: UUID | null;
  RootActivityID: UUID;
  Depth: number;
  /** The payload's encoding; empty means json-v1. */
  Serialization?: string;
}

export interface IdempotencyKeyConfig {
  Key: string;
  Behavior: IdempotencyBehavior;
}

export interface FailureKind {
  Retryable: boolean;
  Reason: string;
  IsTimeout: boolean;
  Details?: RawJSON;
}

export interface RetentionPolicy {
  Completed: Duration;
  Failed: Duration;
  /**
   * How long events of finished activities are kept, apart from their tree; 0
   * keeps them as long as the tree. Events of unfinished activities are kept.
   */
  Events: Duration;
}

export interface IdempotencyResult {
  ExistingID: UUID;
  ExistingParentID?: UUID | null;
}

export interface ActivitySnapshot {
  id: UUID;
  activity_type: string;
  payload?: RawJSON;
  priority: number;
  status: string;
  created_at: Timestamp;
  scheduled_at?: Timestamp | null;
  started_at?: Timestamp | null;
  completed_at?: Timestamp | null;
  current_worker_id?: string | null;
  last_worker_id?: string | null;
  retry_count: number;
  max_retries: number;
  timeout_seconds: number;
  retry_delay_seconds: number;
  metadata?: Record<string, string> | null;
  last_error?: string | null;
  last_error_at?: Timestamp | null;
  status_updated_at: Timestamp;
  score?: number | null;
  lease_deadline_ms?: number | null;
  processing_member?: string | null;
  idempotency_key?: string | null;
  parent_activity_id?: UUID | null;
  root_activity_id?: UUID | null;
  depth: number;
}

export interface ActivityEvent {
  activity_id: UUID;
  timestamp: Timestamp;
  /** A stored event type; see vectors/canonical_event.json. */
  event_type: string;
  worker_id?: string | null;
  detail?: RawJSON;
}

export interface StepRecord {
  Kind: string;
  Name: string;
  State: ResultState;
  Data?: RawJSON;
  CreatedAt: Timestamp;
}

export interface DeadLetterRecord {
  activity: ActivitySnapshot;
  error: string;
  failed_at: Timestamp;
}

export interface DequeuedActivity {
  Activity: QueuedActivity;
  LeaseID: string;
  Attempt: number;
  LeaseDeadline: Timestamp;
}

export interface GetResultArgs {
  activityID: UUID;
}

export interface EnqueueArgs {
  activity: QueuedActivity;
}

export interface DequeueArgs {
  workerID: string;
  timeout: Duration;
  activityTypes?: string[] | null;
}

export interface AckSuccessArgs {
  activityID: UUID;
  result?: RawJSON;
  workerID: string;
}

export interface AckFailureArgs {
  activityID: UUID;
  failure: FailureKind;
  workerID: string;
}

export type ProcessScheduledArgs = Record<string, never>;

export interface RequeueExpiredArgs {
  batchSize: number;
}

export interface YieldArgs {
  activityID: UUID;
  wakeAt: Timestamp;
  workerID: string;
  kind: string;
  step: string;
}

export interface StoreResultArgs {
  activityID: UUID;
  ownerActivityID: UUID;
  result: ActivityResult;
  step: string;
}

export interface WakeWaitingArgs {
  activityID: UUID;
}

export interface SignalActivityArgs {
  activityID: UUID;
  signalID: UUID;
  name: string;
  payload?: RawJSON;
}

export interface LookupIdempotencyActivityIDArgs {
  idempotencyKey: string;
}

export interface CleanupExpiredArgs {
  policy: RetentionPolicy;
  batchSize: number;
}

export interface EnqueueIdempotentArgs {
  activity: QueuedActivity;
}

export interface RecordSpawnLinkedArgs {
  childID: UUID;
  parentID: UUID;
}

export interface GetActivityArgs {
  activityID: UUID;
}

export interface GetActivityEventsArgs {
  activityID: UUID;
  limit: number;
}

export interface GetActivityStepsArgs {
  ownerActivityID: UUID;
}

export interface GetChildrenArgs {
  parentID: UUID;
  offset: number;
  limit: number;
}

export interface GetSubtreeArgs {
  rootID: UUID;
}

export interface ListDeadLetterArgs {
  offset: number;
  limit: number;
}

export interface DequeueBatchArgs {
  workerIDPrefix: string;
  limit: number;
  timeout: Duration;
  activityTypes?: string[] | null;
}

export interface ExtendLeaseForWorkerArgs {
  activityID: UUID;
  workerID: string;
  extendBy: Duration;
}

export interface StoreCheckpointArgs {
  resultID: UUID;
  ownerID: UUID;
  workerID: string;
  result: ActivityResult;
  step: string;
}

export interface EnqueueForWorkerArgs {
  a: QueuedActivity;
  ownerID: UUID;
  workerID: string;
}

export interface EnqueueIdempotentForWorkerArgs {
  a: QueuedActivity;
  ownerID: UUID;
  workerID: string;
}

export interface RegisterDependencyArgs {
  waiterID: UUID;
  resultID: UUID;
  workerID: string;
}

export interface YieldForResultArgs {
  waiterID: UUID;
  resultID: UUID;
  producerID?: UUID | null;
  wakeAt: Timestamp;
  workerID: string;
  kind: string;
  step: string;
}

export interface DequeueBatchEncodedArgs {
  workerIDPrefix: string;
  limit: number;
  timeout: Duration;
  activityTypes?: string[] | null;
  serializations?: string[] | null;
}

export interface AckSuccessEncodedArgs {
  activityID: UUID;
  result?: RawJSON;
  serialization: string;
  workerID: string;
}

export interface SignalActivityEncodedArgs {
  activityID: UUID;
  signalID: UUID;
  name: string;
  payload?: RawJSON;
  serialization: string;
}

/** Each operation's arguments and result. */
export interface Operations {
  GetResult: { args: GetResultArgs; result: ActivityResult | null };
  Enqueue: { args: EnqueueArgs; result: null };
  Dequeue: { args: DequeueArgs; result: QueuedActivity | null };
  AckSuccess: { args: AckSuccessArgs; result: null };
  AckFailure: { args: AckFailureArgs; result: boolean };
  ProcessScheduled: { args: ProcessScheduledArgs; result: number };
  RequeueExpired: { args: RequeueExpiredArgs; result: number };
  Yield: { args: YieldArgs; result: null };
  StoreResult: { args: StoreResultArgs; result: null };
  WakeWaiting: { args: WakeWaitingArgs; result: boolean };
  SignalActivity: { args: SignalActivityArgs; result: null };
  LookupIdempotencyActivityID: { args: LookupIdempotencyActivityIDArgs; result: UUID };
  CleanupExpired: { args: CleanupExpiredArgs; result: number };
  EnqueueIdempotent: { args: EnqueueIdempotentArgs; result: IdempotencyResult | null };
  RecordSpawnLinked: { args: RecordSpawnLinkedArgs; result: null };
  GetActivity: { args: GetActivityArgs; result: ActivitySnapshot | null };
  GetActivityEvents: { args: GetActivityEventsArgs; result: ActivityEvent[] | null };
  GetActivitySteps: { args: GetActivityStepsArgs; result: StepRecord[] | null };
  GetChildren: { args: GetChildrenArgs; result: ActivitySnapshot[] | null };
  GetSubtree: { args: GetSubtreeArgs; result: ActivitySnapshot[] | null };
  ListDeadLetter: { args: ListDeadLetterArgs; result: DeadLetterRecord[] | null };
  DequeueBatch: { args: DequeueBatchArgs; result: DequeuedActivity[] | null };
  ExtendLeaseForWorker: { args: ExtendLeaseForWorkerArgs; result: boolean };
  StoreCheckpoint: { args: StoreCheckpointArgs; result: null };
  EnqueueForWorker: { args: EnqueueForWorkerArgs; result: null };
  EnqueueIdempotentForWorker: { args: EnqueueIdempotentForWorkerArgs; result: IdempotencyResult | null };
  RegisterDependency: { args: RegisterDependencyArgs; result: null };
  YieldForResult: { args: YieldForResultArgs; result: null };
  DequeueBatchEncoded: { args: DequeueBatchEncodedArgs; result: DequeuedActivity[] | null };
  AckSuccessEncoded: { args: AckSuccessEncodedArgs; result: null };
  SignalActivityEncoded: { args: SignalActivityEncodedArgs; result: null };
  WaitForResult: { args: GetResultArgs; result: ActivityResult | null };
}